title: Wearable Data Studio
description: This is the work of the Wearable Data Studio hosted at Amsterdam University of Applied Sciences.
theme: minima # You can change to another Jekyll theme
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
